# Setup
title: Gosha Sawicka
description: Web Developer, Software Engineer, Human Golden Retriever
name:         Project or Site name (Architect Theme)
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

google_analytics:
show_downloads: false

#footer-links:
# github: patyk
# linkedin: goshasawicka
# twitter: goshagalazka

#gems:
#  - jekyll-mentions

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - jekyll-architect-theme-master