title: blog.sawicka.io
email: gosha@sawicka.io
description: >
  Write an awesome description for your new site here.
baseurl: ""
url: "blog.sawicka.io"
twitter_username: goshasawicka
github_username:  goshasawicka
linkedin_username:  goshasawicka

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
   - Gemfile
   - Gemfile.lock
